AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'test/**/*'
    - 'spec/**/*'

# to use run: bundle exec rubocop
# Use plugins instead of require
plugins:
  - rubocop-rails
  - rubocop-performance

# Disable documentation requirement
Style/Documentation:
  Enabled: false

# Allow compact class/module style for controllers
Style/ClassAndModuleChildren:
  Enabled: false

# Disable I18n warnings (we're not using internationalization)
Rails/I18nLocaleTexts:
  Enabled: false

# Allow longer methods for controllers
Metrics/MethodLength:
  Max: 60

# Allow more complex methods
Metrics/AbcSize:
  Max: 65

# Allow longer blocks
Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'config/routes.rb'
    - 'db/seeds.rb'

# Allow longer classes
Metrics/ClassLength:
  Max: 200

# Allow longer lines
Layout/LineLength:
  Max: 140

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

# Allow both single and double quotes
Style/StringLiterals:
  Enabled: false

# Don't enforce database indexes for uniqueness validations
Rails/UniqueValidationWithoutIndex:
  Enabled: false

# Don't enforce dependent option for all associations
Rails/HasManyOrHasOneDependent:
  Enabled: false