AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'test/**/*'
    - 'spec/**/*'

require:
  - rubocop-rails
  - rubocop-performance

# Disable documentation requirement
Style/Documentation:
  Enabled: false

# Allow compact class/module style for controllers
Style/ClassAndModuleChildren:
  Enabled: false

# Allow longer methods for controllers
Metrics/MethodLength:
  Max: 35
  Exclude:
    - 'db/seeds.rb'

# Allow more complex methods
Metrics/AbcSize:
  Max: 30

# Allow longer blocks for routes and seeds
Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'config/routes.rb'
    - 'db/seeds.rb'
    - 'spec/**/*'
    - 'test/**/*'

# Allow longer classes for controllers
Metrics/ClassLength:
  Max: 200

# Allow longer lines
Layout/LineLength:
  Max: 140

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

# Allow both single and double quotes
Style/StringLiterals:
  Enabled: false

# Allow trailing commas
Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

# Allow guard clauses to be more flexible
Style/GuardClause:
  Enabled: false

# Allow rescue without error class in some cases
Style/RescueStandardError:
  Enabled: false

# Allow identical conditional branches
Style/IdenticalConditionalBranches:
  Enabled: false